### PR TITLE
Fix compatibility issues with Allegro CL Modern mode

### PR DESCRIPTION
**Pull request by desiderius**
This pull request add support for Allegro CL Modern Mode
(see http://franz.com/support/documentation/current/doc/case.htm)

Tested with
- Allegro CL 10.1 ANSI and Modern modes
- SBCL 1.3.18

### CODE REVIEW

**Comment by cage2** [comment]
On Tue, Jul 25, 2017 at 09:13:36AM +0000, desiderius wrote:

Hello!

> This pull request add support for Allegro CL Modern Mode
> (see http://franz.com/support/documentation/current/doc/case.htm)

Very good improvement, indeed!

The  only  problem  I  am  having  is that  I  am  not  able  to  load
"marshal-tests" system,  maybe this is just  a fault of my  system but
asdf can not fin the component. :(

Thank you for you contribution, let's wait what @wlbr thinks about it.

Bye!
C.

**Comment by cage2** [comment]
On Tue, Jul 25, 2017 at 08:25:18AM -0700, cage2 wrote:

[...]

> The  only  problem  I  am  having  is that  I  am  not  able  to  load
> "marshal-tests" system,

forget about that.

> maybe this is just  a fault of my  system but
> asdf can not fin the component. :(

it was actually.  :)

Bye!
C.

**Comment by wlbr** [comment]
Hi, thank you for the fix. Sorry for the delay, ove rhere it is time for the big summer vacation.

I'm going merge this. Does anybody know what happens to Quicklisp, if there is a second ASDF system within the package? As the test system is really just loading a single file I think it would be OK to not have ASDF for that.

Bye,
Michael

**Comment by desiderius** [comment]
Hello, thank for the merge :smile: 

About Quicklisp, the second system should not pose any problem as it is a common practice to have a second system for the unit tests (and the main one did not change.)

Of course it is just a convenience for the Allegro CL users because the `(require)` form is deprecated and issue a compile time error with the default settings. Without this we need to `(ql:quickload)` the dependencies before compiling `tests.lisp`.

Regards,
D.

**Pull request merged**
