### PR TITLE
Better error when missing serializable slots

### PR DESCRIPTION
**Pull request by cage2**
Hi!

How are you? I hope you are fine! :)

A kind person from IRC noticed getting a weird error on their code coming from this library, so we investigated and realized that there was actually a bug in their code but the library failed to print an error that could gives some help about what was happening.

So i am trying to fix that with this patch. ;)

Also i changed a bit a test because the code will not compile as is (at least on SBCL 2.1.1)

Take care!
Bye!
C.

### CODE REVIEW

**Comment by Zulu-Inuoe** [comment]
This would disallow having `class-serialized-slots` return `nil` to mean "no slots please", which I could see causing issues, and is (IMO) a valid use-case

**Comment by cage2** [comment]
Hi!

> This would disallow having  `class-serialized-slots` return `nil` to
> mean "no  slots please", which  I could  see causing issues,  and is
> (IMO) a valid use-case

What you write does makes sense to me, i just pushed some changes that
will instance  a class with  no serializable slots with  values filled
with the expressions got from its :initform.

Anyway i  have kept the error  signalling; can be switched  on using a
special variable.

Do you think is this behaviour OK?

Bye and thank you for your help!
C.

**Comment by Zulu-Inuoe** [comment]
This is just my opinion, so take it with a grain of salt:

It seems (to me) that what you wanted to address, was to improve 'debuggability' by signaling on a common error of forgetting to specialize `class-persistent-slots`.

That given, using a special variable, and setting it to default to `nil`, you're back at square one where (especially somebody new to the library) would not be be told of 'no specialization'.

Additionally, by putting it behind a special variable, it opens up more headaches where maybe somebody rebound it under/above you or globally, and say my objects are in some cases not meant to serialize any slots, you'd start getting false positive errors.

So, no, I don't think this is a solution to the problem. And unfortunately I can't think of a solution either.

But hey maybe others (including the author) disagrees.

**Comment by wlbr** [comment]
To be honest - I am outta Lisp since quite some years. I am afraid that my thoughts would not really lead to a lisp intuitive solution. So I leave that to your discussion.

I would recommend that we  think twice about any consequences for our existing users, as the lib has really a lot a (transitive) projects using it.

**Comment by cage2** [comment]
Hi!

> This is just my opinion, so take it with a grain of salt:

No problem, discussion is good and helps a lot! :)

> It seems  (to me) that  what you wanted  to address, was  to improve
> 'debuggability'  by signaling  on a  common error  of forgetting  to
> specialize `class-persistent-slots`.

True!  To  be honest  the library  already signal  that but  the error
message is  horrible, totally uninformative.   So i just  improved the
error, but  then you convinced  me that there  are no reasons  (well i
still think there are  a few, actually ;-)) to signal  an error at all
so i switched to a strategy that, when an user does not specialize the
method  to return  a list  of  serializable slots,  just assumes  all
should  be serialized  with the  default  value for  each slot  (using
:initform), and this is the default that this patch proposes.

> That given, using  a special variable, and setting it  to default to
> `nil`, you're back  at square one where (especially  somebody new to
> the library) would not be be told of 'no specialization'.

Also true!  'nil'  means: "does not signal error and  assume all slots
need  to  be serialized  with  a  default value"  but  if  no list  of
serializable slots has  been indicated from the user the  best guess i
can make is that all need to be serialized.

>  Additionally, by putting it behind  a special variable, it opens up
> more headaches  where maybe somebody  rebound it under/above  you or
> globally,  and  say my  objects  are  in  some  cases not  meant  to
> serialize any slots, you'd start getting false positive errors.

I can see the point with  the special variable (that probably could be
removed so that never an error is signalled) but i also find difficult
to understand  this: if all slots  are "transient", so to  say, is not
the strategy  explained (that i  tried to explain, actually  :)) above
good enough:  just serialize a  class with  default value for  all the
slots?

>  So,  no, I  don't think  this  is a  solution to  the problem.  And
> unfortunately I can't think of a solution either.

That's OK, probably i need to think about that a bit more! :)

Bye and thank you again!
C.

**Comment by cage2** [comment]
Hi happy to hear you again!!

> To be honest -  I am outta Lisp since quite some  years. I am afraid
> that  my  thoughts  would  not  really  lead  to  a  lisp  intuitive
> solution. So I leave that to your discussion.

>  I would  recommend that we  think twice about any  consequences for
> our  existing users,  as the  lib has  really a  lot a  (transitive)
> projects using it.

Do not worry, i  am too a regular user of this  library and care about
it :) So, please, be confident that i will try (i can not guarantee but
i will do my best) to be very  careful to not make lives of other user
more difficult in this already hard times. :)

Bye!
C.

**Comment by cage2** [comment]
Hi!

I have wrote a quick code snippet to further illustrate my proposal, i think the code could be a better job at explaining my patch instead of my bad English :)

``` lisp
(in-package :cl-user)

(require :marshal)

(use-package :marshal)

(defclass a-class ()
  ((m
    :accessor m
    :initform 'default
    :initarg  :m)
   (n
    :accessor n
    :initform 'default
    :initarg  :n)))

(defmethod print-object ((object a-class) stream)
  (print-unreadable-object (object stream :type t :identity nil)
    (with-accessors ((m m)
                     (n n)) object
      (format stream "m: ~a, n: ~a" (m object) (n object)))))

(defmethod ms:class-persistent-slots ((object a-class))
  '(m n))

(defun println (name stuff)
  (format t "~&name ~a => ~a~%" name stuff))

(defun serialize-and-restore (stuff)
  (ms:unmarshal (ms:marshal stuff)))

(defun test ()
  (let ((object (make-instance 'a-class :m 'defined :n'defined)))
    (println "test" (serialize-and-restore object))))

(test)

(defmethod ms:class-persistent-slots ((object a-class))
  '(m))

(defun test-2 ()
  (let ((object (make-instance 'a-class :m 'defined)))
    (println "test-2" (serialize-and-restore object))))

(test-2) 

(defmethod ms:class-persistent-slots ((object a-class))
  nil)

(defun test-3 ()
  (let ((object (make-instance 'a-class)))
    (println "test-3" (serialize-and-restore object))))

(test-3) 

(defun test-4 ()
  (let ((object (make-instance 'a-class))
        (*signal-unserializable-class*  t))  ;   this  keeps  the  old
                                           ; behaviour,  i.e.  signals
                                           ; an error
    (println "test-4" (serialize-and-restore object))))

(test-4)
```

Running this code will print on the REPL:

``` lisp
name test => #<A-CLASS m: DEFINED, n: DEFINED>
name test-2 => #<A-CLASS m: DEFINED, n: DEFAULT>
name test-3 => #<A-CLASS m: DEFAULT, n: DEFAULT>
```
the last test `test-4` will signal an error like the library does now (but the message is not clear like this one)

Excluding the error (that could go away, likely) I think there is a consistent pattern that I can see here. When a slot is not specified via specializing the method `ms:class-persistent-slots`, restoring will fills that slot with the results of the expression passed to `:initform` when the class was defined.

I propose to remove the special variable `*signal-unserializable-class*` from this patch and keep the behaviour illustrated above as the default.

Bye!
C.   

PS: FWIW the code above is released under [MIT License](https://opensource.org/licenses/MIT)

**Comment by cage2** [comment]
Hi!

I removed the special variable `*signal-unserializable-class*` from this patch. As i think this changes improves the library and are backward compatible, if there are no objections, i am going to merge this in the next days.

Looking forward for any comments! 

Bye!
C.

**Comment by cage2** [comment]
Hi!

I think it is OK to merge this patch, if any problem arise we can just revert the code.

Bye!!!
C.

**Pull request merged**
